using System;

namespace CsTsCoder.Spin
{
    public class Program
    {
        /// <summary>
        /// Defines the entry point of the application.
        /// </summary>
        /// <param name="args">The arguments.</param>
        static void Main(string[] args)
        {
            if (args.Length != 2)
            {
                Console.WriteLine("Assuming testing...");

                args = new string[2] {"", ""};
                
                //works for vs code
                args[0] = "../../../csharp/dtos";
                args[1] = "../../../typescript/dtos";
            }

            Program.StartService(args);
        }

        public static void StartService(string[] args) {
            var convertService = new CoderService((logString, logArgs) => Console.WriteLine(logString, logArgs))
            {
                InputDirectory = args[0],
                OutputDirectory = args[1],
                AutoGeneratedTag = true,
                EnumValues = CsTsCoder.Shared.Enums.EnumValue.Default,
                PathStyle = CsTsCoder.Shared.Enums.PathStyle.Kebab

            };
            
            convertService.Execute();
        }


    }
}
