name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Installing SDKs
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: | 
            3.1.x
            5.0.x
            6.0.x

      - name: Build & Pack
        run: dotnet pack ./src/CsTsCoder/CsTsCoder.csproj -c Release -o out

      - name: Push to NuGet.org
        run: dotnet nuget push ./out/$(ls ./out) -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
        
